ampa_homepage:
    path:     /
    defaults: { _controller: AmpaBundle:Default:index }

ampa_ropa:
    path:     /ropa
    defaults: { _controller: AmpaBundle:Ropa:ropa }

ampa_complementos:
    path:     /complementos
    defaults: { _controller: AmpaBundle:Default:complementos }

ampa_insertarRopa:
    path:     /cud/insertar
    defaults: { _controller: AmpaBundle:Ropa:insertar }

ampa_actualizarRopa:
    path:     /cud/actualizar/{id}
    defaults: { _controller: AmpaBundle:Ropa:actualizar }

ampa_deleteRopa:
    path:     /cud/delete/{id}
    defaults: { _controller: AmpaBundle:Ropa:delete }

ampa_mostrarMarca:
    path:     /mostrarMarca
    defaults: { _controller: AmpaBundle:Marca:mostrarMarca }

ampa_insertarMarca:
    path:     /cud/insertarMarca
    defaults: { _controller: AmpaBundle:Marca:insertarMarca }

ampa_actualizarMarca:
    path:     /cud/actualizarMarca/{id}
    defaults: { _controller: AmpaBundle:Marca:actualizarMarca }

ampa_deleteMarca:
    path:     /cud/deleteMarca/{id}
    defaults: { _controller: AmpaBundle:Marca:deleteMarca }

# Elementos utilizados en la prueba predefinida la talla a mostrar Talla:L
ampa_muestraNombre:
    path:     /muestraNombre/{talla}
    defaults: { _controller: AmpaBundle:Ropa:muestraNombre, talla:L }

ampa_muestrame:
    path:     /muestrame/{id}
    defaults: { _controller: AmpaBundle:Ropa:muestrame}
