usuarios:
    resource: "@usuariosBundle/Controller/"
    type:     annotation
    prefix:   /usuarios

ampa:
    resource: "@AmpaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /usuarios/logout
