# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        usuariosBundle\Entity\usuarios:
            algorithm: bcrypt


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 1234
                        roles: 'ROLE_ADMIN'
        my_db_provider:
            entity:
                class: usuariosBundle:usuarios
                property: username


    access_control:
    - { path: ^/usuarios/admin, roles: ROLE_ADMIN }
    - { path: ^/cud, roles: ROLE_ADMIN }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        usuarios:
            pattern: ^/
            anonymous: ~
            provider: my_db_provider
            form_login:
                login_path: /usuarios/login
                check_path: /usuarios/login
            logout:
                path:   /usuarios/logout
                target: /usuarios/login

        admin:
            http_basic: ~
            pattern: ^/usuarios/admin

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
