<?php

namespace AmpaBundle\Repository;

/**
 * RopaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RopaRepository extends \Doctrine\ORM\EntityRepository
{
}
